show_for:
  default: everyone
  type: enum
  choices:
    - everyone
    - logged_in
    - logged_out

show_on:
  default: top_menu
  type: enum
  choices:
    - top_menu
    - homepage
    - all
  description: top_menu refers to the <a href="/admin/site_settings/category/all_results?filter=top_menu">top menu site setting</a>

svg_icons:
  default: "palette|fab-discourse"
  type: "list"
  list_type: "compact"
